---
- name: config - Setup monitrc
  template:
    src: monitrc.j2
    dest: /etc/monit/monitrc
    owner: root
    group: root
    mode: 0700
  notify: restart monit

- name: config - Setup webinterface
  template:
    src: webinterface.j2
    dest: /etc/monit/conf.d/webinterface
    owner: root
    group: root
    mode: 0644
  notify: restart monit

- name: config - Setup apache2 config http
  template:
    src: apache2.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: 0644
  notify: restart monit
  notify: restart apache2
  when: enable_ssl == false

- name: config - Setup apache2 config https
  template:
    src: apache2_ssl.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: 0644
  notify: restart monit
  notify: restart apache2
  when: enable_ssl == true

- name: config - Setup mail alerts
  template:
    src: mail.j2
    dest: /etc/monit/conf.d/mail
    owner: root
    group: root
    mode: 0644
  notify: restart monit
  when: monit_mail_enabled
