---
- name: install apache2
  apt: name=apache2 update_cache=no state=latest
- name: enable proxy_http
  apache2_module: name=proxy_http state=present
  notify:
    - restart apache2
- name: enable ssl
  apache2_module: name=ssl state=present
  notify:
    - restart apache2
  when: enable_ssl == true
