---
- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C={{ ssl.cert.C }}/ST={{ ssl.cert.ST }}/L={{ ssl.cert.L }}/O={{ ssl.cert.O }}/CN={{ fqdn }}" -days {{ ssl.cert.days }} -keyout {{ ssl.cert.path.key }} -out {{ ssl.cert.path.cert }} -extensions v3_ca creates={{ ssl.cert.path.cert }}
- name: change file permissions
  file: path={{ ssl.cert.path.key }} owner={{ ssl.cert.user }} group={{ ssl.cert.user }} mode={{ ssl.cert.mode }}
