---
- hosts: all
  sudo: true
  roles:
    - common
    - apache2
    - sslcert
    - ganglia
  vars:
    fqdn: vm1.yevhen.net
# Variables related to application monitoring.
    app:
      name: app_requests
      monitoring: true
      monitoring_url: "http://10.0.2.2:11080/app/status"
      collection_time: 10
      time_threshold: 20
      value_threshold: 10
# Variables related to ganlgia. Saved as it was in original github repo.
    is_ganglia_web: 1
# Variables related to SSL
    ssl:
      enable: true
      cert:
        user: www-data
        mode: o-rwx
        C: US
        ST: Oregon
        L: Portland
        O: IT
        days: 365
        path:
          key: /etc/apache2/server.key
          cert: /etc/apache2/server.crt
