---
- hosts: all
  sudo: true
  roles:
    - common
    - apache2
    - sslcert
    - ganglia
  vars:
    fqdn: vm1.yevhen.net
    app_monitoring_url: "http://10.0.2.2:11080/app/status"
    app_monitoring: true
    app_collection_time: 10
    app_time_threshold: 20
    app_value_threshold: 10
    is_ganglia_web: 1
    enable_ssl: true
    ssl_cert_user: www-data
    ssl_cert_mode: go-rwx
    ssl_cert_C: US
    ssl_cert_ST: Oregon
    ssl_cert_L: Portland
    ssl_cert_O: IT
    ssl_cert_days: 365
    ssl_cert_keypath: /etc/apache2/server.key
    ssl_cert_certpath: /etc/apache2/server.crt
