---
- hosts: all
  sudo: true
  roles:
    - common
    - apache2
    - sslcert
    - ganglia
  vars:
    fqdn: vm1.yevhen.net
    app_monitoring_url: "http://10.0.2.2:11080/app/status"
    app_monitoring: true
    app_collection_time: 10
    app_time_threshold: 20
    app_value_threshold: 10
    is_ganglia_web: 1
        ssl:
      enable: true
      cert:
        user: www-data
        mode: o-rwx
        C: US
        ST: Oregon
        L: Portland
        O: IT
        days: 365
        path:
          key: /etc/apache2/server.key
          cert: /etc/apache2/server.crt
