---
- hosts: all
  sudo: true
  roles:
    - common
    - apache2
    - sslcert
    - app
  vars:
    fqdn: vm2.yevhen.net
#Variables related to application
    app:
      port: 8765
      bind_addr: 127.0.0.1
      web_location: app
      daemon_name: app
      status_page: /status
# Variables related to SSL
    ssl: 
      enable: true
      cert: 
        user: www-data
        mode: o-rwx
        C: US
        ST: Oregon
        L: Portland
        O: IT
        days: 365
        path:
          key: /etc/apache2/server.key
          cert: /etc/apache2/server.crt
